services:
  exercise-service:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    command: python -m uvicorn src.main:app --host 0.0.0.0 --port 8002 --reload
    networks:
      - codesnap-net

networks:
  codesnap-net:
    external: true
    name: shared-codesnap-network